### ISSUE TITLE
بررسی آپلود رفرنس و انیمیشن

### ISSUE THREAD

**Issue by shahabshn** [includeamin/animup-docs#120]
mohandes 2 ta refrence darj kardim ke yeki seriali yeki ham cinamaii
seriali ro to app namayesh mide vali cinamaii naa
baraye har 2ta yek animation ham darj kardim vali hich kodom to app namayesh dade nemishe vali to database baraye cinamaii ezafe shode vali baraye seriali na

@includeamin

**Comment by includeamin** [comment]
```
    valid_animation_types = {"serial": "serial", "serial-sinamae": "serial-sinamae"}

```

**Comment by includeamin** [comment]
aln kilit un siname shoaro zadam serial-sinamae
va ok shod
