### ISSUE TITLE
بررسی لود موور

### ISSUE THREAD

**Issue by shahabshn** [includeamin/animup-docs#134]
mohandes vaghti (انیمیشن های بومی) mizanam hamchin khataii mide vaghti none-lang mizanam 
{"State": true, "Description": "{\n \"Items\": [],\n \"Title\": [\n \"unknown top level operator: $ne\"\n ]\n}"}
vali vaghti lang mizanam khataii nemide vali mohtavaii nadare
"State": true,
    "Description": "[\n    {\n        \"Items\": [],\n        \"Title\": \"\ا\ن\ی\م\ی\ش\ن \ه\ا\ی \ب\و\م\ی\"\n    }\n]"

mobile/homepage/more/none-lang

@includeamin

**Comment by includeamin** [comment]
bartaraf shod in mored
