### ISSUE TITLE
مشکل در حذف انیمیشن

### ISSUE THREAD

**Issue by shahabshn** [includeamin/animup-docs#135]
mohandes zamane delete animation to panel hamchin khataii mide
admin/animation/delete/' + id

{"State": false, "Description": ["Cannot use the part (AnimationId) of (SubAnimationList.AnimationId) to traverse the element ({SubAnimationList: [ { AnimationId: \"5dc3f85b2c90730009d4423f\", Anim_Language: \"\u062a\u0631\u06a9\u06cc\" }, { AnimationId: \"5dc7e27bc4655d0009d13660\", Anim_Language: \"\u06a9\u0631\u0645\u0627\u0646\u06cc\" } ]})"]}

@includeamin

**Comment by includeamin** [comment]
barresi mkonm etela midam
