### ISSUE TITLE
بررسی لینک آپدیت balance

### ISSUE THREAD

**Issue by shahabshn** [includeamin/animup-docs#141]
zamani ke android akharin balance ro bekhad update kone khatare ino dar web darim ke user biad link T token va... ro begire va kharej az barname balance ro afzayesh bede
lotfan baresi beshe ke ba in link emkane afzayeshe balance hast ya na

@includeamin

**Comment by includeamin** [comment]
in ghesmato bayad be webkar bgir az backendesh be server request bed
har kari konim bazamn dide mishe


<fron-end> -----> <front-end-backend> ----> < our-web-service>
