### ISSUE TITLE
اعمال درصد زمان ثبت تراکنش

### ISSUE THREAD

**Issue by shahabshn** [includeamin/animup-docs#142]
zamani ke user yeki az package haro baraye mesal 10000 tomani ro entekhab mikone, user 10000 toman pol pardakht mikone vali balance 10500 (5 darsad) sharj mishe
va darsad ha baraye mabalegh mokhtalef hastesh

@includeamin

**Comment by includeamin** [comment]
baraie kudum url mishe in hamun charge?

**Comment by shahabshn** [comment]
users/accounting/balance/charge

@includeamin
