### ISSUE TITLE
لیست تراکنش کاربر

### ISSUE THREAD

**Issue by shahabshn** [includeamin/animup-docs#149]
@includeamin

**Comment by includeamin** [comment]
https://github.com/includeamin/animup-docs/blob/master/AccountingService/bank_gate_away.md

**Comment by shahabshn** [comment]
mohandes linke tarakoneshe har user baraye namayesh dar mobile

@includeamin

**Comment by includeamin** [comment]
khob? zadam dg linkeshm hast
