### ISSUE TITLE
ویرایش لینک دریافت بنر پنل

### ISSUE THREAD

**Issue by shahabshn** [includeamin/animup-docs#156]
mobile/banners

mohandes bi zahmat language ham response beshe

@includeamin

**Comment by includeamin** [comment]
bug nist vali okaye anjam midam

**Comment by includeamin** [comment]
in bishtar zaman mibare chon 2  ta service o bas edit konm ta beshe in karo konm

**Comment by includeamin** [comment]
anjam shod nokte inke  language zaman ezafe shodan banner ezafe mishe pas fght banner haie jadid in meghdaro daran bayad hame banner haro pak koni va banner jadid add koni


mn naresidam test konm pas bi zahmat test konin va be man begin agar moshkeli dasht
agar ham na close kon
