### ISSUE TITLE
ویرایش لینک آمار

### ISSUE THREAD

**Issue by shahabshn** [includeamin/animup-docs#173]
admin/accounting/records/records-query?query-key=Last30Day

mohandes bi zahmat faghat tarakonesh haye verify shode jam beshe  

@includeamin

**Comment by includeamin** [comment]
okay kardam ye args e dg ham ezafe kardam
be name status k betunin in amaro bara status haie motefavet ham dashte bashin :D
```
https://api.doobletoon.ir/v1/accountingservice/admin/accounting/records/records-query?query-key=Last30Day&status=pending
```
