### ISSUE TITLE
تغییر در ویرایش انیمیشن پنل

### ISSUE THREAD

**Issue by shahabshn** [includeamin/animup-docs#174]
mohandes zamani ke mikhaim name animation ro edit konim peyghame (already same name animation) mide, age yadet bashe hamino to sabte animation dashtiom ke to sakhtare jadid bartaraf shod va gharar shod ke name tekrari moredi nadashte bashe , lotfan link edit ham in mahdodiat gerefte she

animation/update

@includeamin

**Comment by includeamin** [comment]
barashte shod
