### ISSUE TITLE
بازبینی لینک اطلاعات انیمیشن

### ISSUE THREAD

**Issue by shahabshn** [includeamin/animup-docs#175]
mohandes age yadet bashe chand roze ghabl link zir ro edit kardi ke ghesmate pishnehade animation to ye array gharar begire, moshkel injast ke to pishnehade language moshabeh ya pishnehadi nemide ya age bede yeki ya 2ta mide dar hali ke masalan animatiuon be zabane torki ziad vojod dare vali pishnehadi nemide

mobile/animation/(animId)

@includeamin

**Comment by includeamin** [comment]
shab barresi mikonm
