### ISSUE TITLE
اطلاعات انیمیشن

### ISSUE THREAD

**Issue by shahabshn** [includeamin/animup-docs#20]
لینک مشاهده انیمشن ، تریلر، کاور، پوستر ترجیحا همراه با اطلاعات انیمیشن

**Comment by ehssamimi** [comment]
ما لینک برای دریافت اطلاعات انیمشن داریم 
publisher/animations/myanimation
تو این ولی لینکی برای پوستر ،کاور و انیمشن ها نیست اینو اگه میشهیه کاری بکن

**Comment by includeamin** [comment]
@shahabshn 
shahab in linko k dari to
