### ISSUE TITLE
حذف کاربران

### ISSUE THREAD

**Issue by shahabshn** [includeamin/animup-docs#21]
لینک حذف کاربران ایجاد شده با شماره تلفن

**Comment by ehssamimi** [comment]
حذف کاربر با شماره تلفن  تا بتونیم صفحه لاگین رو اوکی کنیم 
@includeamin

**Comment by includeamin** [comment]
/temp/admin/delete/user/<phonenumber> 3002
@ehssamimi

**Comment by includeamin** [comment]
/temp/admin/delete/user/<phonenumber>

**Comment by includeamin** [comment]
```
/temp/admin/delete/user/<phonenumber>
```
