### ISSUE TITLE
بنر

### ISSUE THREAD

**Issue by shahabshn** [includeamin/animup-docs#23]
لینک اضافه کردن ، مشاهده و حذف بنر

**Comment by includeamin** [comment]
@ehssamimi @shahabshn 
zade budam tu animup ghadimi hast aln midam url hasho

**Comment by includeamin** [comment]
# add banner

```
URL /admin/banners/upload/<animationid>
Method POST
Body FileName Banner [ file ]
Header Header PhoneNumber
```

**Comment by ehssamimi** [comment]
مشاهده بنر ها هم اگه داری به همرا لینک حذفشون رو هم بده
@includeamin

**Comment by ehssamimi** [comment]
اقا من فعلا مشاهده بنر رو از موبایل می گیرم اما به اسم انیمشن هم نیاز دارم الان فقط id رو داره 
@includeamin

**Comment by includeamin** [comment]
/admin/banners/delete/<id>
/mobile/banner/click/<id>

**Comment by includeamin** [comment]
@ehssamimi tu body ye AnimationName ham ezafe shode check kon

**Comment by ehssamimi** [comment]
> ```
> /admin/banners/delete/<id>
> /mobile/banner/click/<id>
> ```

اقا این click/id چیه ؟

**Comment by ehssamimi** [comment]
بعد ببین من وقتی میخوام بنر رو اضافه کنم از دستور 
admin/banners/upload/${animID} استفاده می کنم 
قبلا اوکی بود اما الان بهم
bad request 400
رو میده که احتمالا به خاطر اضافه نکرد اسم انیمیشنه اون اسم کلید برای اضفه کردن اسم انیمیشن رو اگه بدی فکر کنم اوکی شه 
@includeamin

**Comment by includeamin** [comment]
> > ```
> > /admin/banners/delete/<id>
> > /mobile/banner/click/<id>
> > ```
> 
> اقا این click/id چیه ؟

aln kare khasi nemikone baraie to ham nist tu mobile e bara inke har kilik o beshmorim ma

**Comment by includeamin** [comment]
> admin/banners/upload

AnimationName kilideshe test kon behem bgu

**Comment by ehssamimi** [comment]
اقا اوکی شد برای اضافه کردن بنر اما مشاهدش هنوز بدون اسمه :
http://193.176.243.180:3004/mobile/banners
این ادرسشه

**Comment by includeamin** [comment]
elslah shod aln mituni test koni

**Comment by ehssamimi** [comment]
> elslah shod aln mituni test koni
امین هنوز اوکی نشده نمیدونم بهخاظز اینه که ثبت نمی کنه اسم رو یا نمایش نمیده !!
و اینکه برای حذف بنر هم 
State: false, Description: "NF"}
اینو داریم

**Comment by includeamin** [comment]
> http://193.176.243.180:3004/mobile/banners

ino check kon baz build nashode bud

**Comment by ehssamimi** [comment]
امین اسم انیمشن ها الان میشه دید 
اما همچنان برای حذف بنر ما این ارور رو داریم :Description: "NF" 
یعنی چی؟؟
@includeamin

**Comment by includeamin** [comment]
> امین اسم انیمشن ها الان میشه دید
> اما همچنان برای حذف بنر ما این ارور رو داریم :Description: "NF"
> یعنی چی؟؟
> @includeamin

baraie haz az AnimationId ehtemaln estefade mikardi  man  id o nazashte budam tush yadam rafte bud aln key . ''Id" ezafe shode ba un hz fkon test shod delete shode
