### ISSUE TITLE
Publisher links with images

### ISSUE THREAD

**Issue by includeamin** [includeamin/animup-docs#24]
@ehssamimi 
salam, agha hame url hae k ax tush hast k mikhi link beshan o mituni bedi?

**Comment by includeamin** [comment]
baraie publisher

**Comment by ehssamimi** [comment]
برای ثبت عکس های ناشر فقط یک ادرسه :
publisher/profile/complete
که خب یه کلید هایی میگیره
photo ssnPhoto AgahiImage RuznameRasmiImage
اما برای گرفتن عکس ها 
publisher/uploads/profile
برای گرفتن بقیه عکس های ناشر هم 
publisher/getinfo

**Comment by ehssamimi** [comment]
برای انییمشن ها ها روهم میخوای؟
@includeamin

**Comment by includeamin** [comment]
> برای انییمشن ها ها روهم میخوای؟
> @includeamin

yes yes
