### ISSUE TITLE
تایید کاربران

### ISSUE THREAD

**Issue by ehssamimi** [includeamin/animup-docs#25]
اقا ببین لینک تایید کاربران اینه:
admin/users/status/${id}/Confirm
بدون body
به من error:
HTTP_PHONENUMBER 
میده
@includeamin

**Comment by includeamin** [comment]
headet Token Phonenumber o midi?

**Comment by ehssamimi** [comment]
امین اینو یه چک بکن

**Comment by ehssamimi** [comment]
امین اینو یه چک بکن 
@includeamin
