### ISSUE TITLE
Test Links

### ISSUE THREAD

**Issue by includeamin** [includeamin/animup-docs#27]
salam ehsan link haie k inja mizarm bara unjae hast k link ax ha taghir karde har kudumo k mizarm test kon natije . o begu bem

**Comment by includeamin** [comment]
- [ ] /admin/publishers/get/<status>

**Comment by includeamin** [comment]
/admin/publisers/uploads/get/<image>/<phonenumber>
in link age yadet bashe baraie gereftan item haie publisher bude ba estefade az in link mituni link ax haie publisher o bgiri

**Comment by includeamin** [comment]
/admin/publisher/info/<phonenumber>

**Comment by includeamin** [comment]
/admin/users/get/inprogress

**Comment by includeamin** [comment]
/admin/users/get/<id>

**Comment by includeamin** [comment]
/admin/users/get/accepted

**Comment by includeamin** [comment]
/admin/users/get/baned

**Comment by includeamin** [comment]
/publisher/animation/<id>
link video ha va poster va trailer va cover eslah shod

**Comment by includeamin** [comment]
/publisher/animations/myanimation
in link tush tasvir dashti?

**Comment by includeamin** [comment]
@ehssamimi

**Comment by ehssamimi** [comment]
> /publisher/animations/myanimation
> in link tush tasvir dashti?

اقا یک کاور تو این لینک بزاری اوکیه

**Comment by includeamin** [comment]
akhari o ham ok kardm test kon
