### ISSUE TITLE
login-logout

### ISSUE THREAD

**Issue by ehssamimi** [includeamin/animup-docs#29]
logout:
get :http://193.176.242.165:3002/users/logout
Token:35a9eacf65c03bc44f3b45d1f4fff855764b94c78b13c7bc512bd06f5b4ca3a4
PhoneNumber:09112561701
log in :
Url: publisher/login
body:PhoneNumber
--entercode:
url:users/verifyCode/${userphone}/${PhoneNumber}
سیستم لاگین اوکیه یعنی توکن و ای دی رو بهمون میده اما مشکل وقتیه که بعد از لاگین یه درخواست دیگه با اون توکن ای دی میدیم که میگه باید  لاگین شوید!

**Comment by ehssamimi** [comment]
@includeamin

**Comment by includeamin** [comment]
tamas gereftam ye 7 bari javab nadadi :,((((
2 3 ta taghirat dadm check kon
baraie to 2 ta token bud tu database ajib bud 
aln eslah kardam test kon bem bgu
@ehssamimi

**Comment by ehssamimi** [comment]
amin baraye baghie user ha ok shod!merci 👍 
 ama account man nemite logout besham  shayad chon user token avaz shode aghe injorie  token jadid ro bede behem

**Comment by includeamin** [comment]
okaye okaye check mikonm bara toro ham
