### ISSUE TITLE
تغییرات 1398-05-17

### ISSUE THREAD

**Issue by shahabshn** [includeamin/animup-docs#30]
خروجی mobile/homepage برای item :
   - کلید گویش اضافه شود
   - نام کلید Poster به Cover تغییر کند

خروجی users/bookmark :
   - کلید ناشر اضافه شود (Publisher)
   - کلید های Director و Producer و Create_at حذف شود
   - به جای کاور، پوستر دریافت شود.

خروجی mobile/animations/search :
   - نام ناشر اضافه شود (Publisher)
@includeamin

**Comment by includeamin** [comment]
homepage o anjam dadam mituni test koni natije o begi bem

**Comment by includeamin** [comment]
5 min dg test kon dare build mishe

**Comment by includeamin** [comment]
bookmark ha anjam shode test kon uno ham

**Comment by includeamin** [comment]
tu search ham name publisher ezafe shode
