### ISSUE TITLE
عکس دیفالت در مشاهده اطلاعات کاربران 

### ISSUE THREAD

**Issue by ehssamimi** [includeamin/animup-docs#49]
عکس دیفالت برای کاربرانی که بن میشن یا عکسشون به حالت دیفالت تبدیل میشه 
admin/users/get/baned
مشکل داره

**Comment by includeamin** [comment]
salam in ghesmt ham okay shode agar karbari axe dafault ghadidmi dare ba upadte hame ok mishe
