### ISSUE TITLE
اصلاح لینک دریافت پیام ادمین

### ISSUE THREAD

**Issue by shahabshn** [includeamin/animup-docs#52]
mohandes vaghti to panel payam sabt mikonad android faghat 1 payamo namayesh mide
users/admingroupmessage/get @includeamin

**Comment by includeamin** [comment]
bishtar tozih midi?

**Comment by shahabshn** [comment]
vaghti admin payam baraye user ha sabt mikone ba link daryaftie message ke dadi har dafe faghat 1 message daryaft mishe, ye message sabet @includeamin

**Comment by includeamin** [comment]
inam okay shode
