### ISSUE TITLE
لینک ها (فوری)

### ISSUE THREAD

**Issue by shahabshn** [includeamin/animup-docs#59]
lotfan link haye khaste shode ro befrestid :

- daryafte daste bandi
- daryafte genre ha
- daryafte goyesh ha
- daryafte rade seni

- ersale etelaate animation (sabte animation)
- daryafte my animation
- edit animation @includeamin  @ehssamimi

**Comment by ehssamimi** [comment]
Port : 3003
دسته بندی:
/category
/category/add
/category/delete
گویش:
/language
/language/add
/language/delete
ژانر ها
/genre
genre/add
genre/delete
نگ ها :
/tag
tag/add
tag/delete
رده سنی:
/age
age/add
age/delete
اضافه کردن اطلاعات انیمیشن :
animation/update
animation/add
port:3003
گرفتن اطلاعات انیمیشن هر ناشر:
publisher/animations/myanimation
port:3003

**Comment by ehssamimi** [comment]
body:{ Name , Date, Director, PublisherName, Producer, Genre , Age, Language, Description, Category, IsSerial , Tags, ProducerGroup }
اگر قرار باشه آپدیت بشه باید ایدی انیمشن هم با کلید 
AnimationId
اضافه بشه
