### ISSUE TITLE
ثبت تعداد کامنت برای انیمیشن

### ISSUE THREAD

**Issue by shahabshn** [includeamin/animup-docs#73]
bad az sabte comment baraye namayeshe tedade comment az Comment_Count estefade mikonam ke hamishe 0 hast
@includeamin

**Comment by includeamin** [comment]
url haie k ina tush moshkel dare o ham bezar lotfan

**Comment by includeamin** [comment]
in mored ham anjam shod zamani k commenti accept mishe tedadesh ezafe mishe na zamani k comment gozashte mishe
