### ISSUE TITLE
مشکل در پیام

### ISSUE THREAD

**Issue by shahabshn** [includeamin/animup-docs#76]
zamani ke admin 1 payame gorohi sabt mikone unReadAdminGroupMeessage = true nemishe va man motevajeh message jadid nemisham

zamani ke admin baraye 1 user khas message mifreste unReadMessage = true mishe vali bad az inke man dar mobile daryaftesh kardam meghdaresh false nemishe va hamihse be onvane message jadid shenasaii mishe

@includeamin

**Comment by includeamin** [comment]
in barresi shod ye seri eslahat anjam shod test kon etela bede bem
