### ISSUE TITLE
بررسی تعداد نظرات انیمیشن

### ISSUE THREAD

**Issue by shahabshn** [includeamin/animup-docs#81]
/mobile/animation/<animId>
mohandes zamani ke chand comment baraye animation sabt beshe tedade namayeshi mobile ba tedade comment ha dar samte admin yeki nist

/animation/comments/<animId>
zamane daryafte liste comment haye yek animation ham tedade daryafti yeki nist

@includeamin

**Comment by includeamin** [comment]
#83
