### ISSUE TITLE
اصلاح لینک دریافت نظرات انیمیشن

### ISSUE THREAD

**Issue by shahabshn** [includeamin/animup-docs#83]
/animation/comments/<animId>
mohandes link image ro loftan baresi kon
chon be nazaram dorost nist 

@includeamin

**Comment by includeamin** [comment]
shahab jan bbin to comment haro dasti az database pack karde budi bara hamin shomare comment ha  aln k man didam kolan 3 ta comment to database hast k taaed shodan baraie ye animation hamun 3 ta ham namaiesh dare dade mishe be dorosti dalil eshtebah budan tedad comment ha ine k dasti pak shode va system tu halate dasti nmitune befahme k delete shode! :D

**Comment by includeamin** [comment]
bazam barresi kon man aln tedad comment haro dobare mikonm 3 ta ta tanzim bashe

**Comment by shahabshn** [comment]
aha, khob mohandes linke image ke behem mide linke dorosti nist ke man betonam axe profile user ro namayesh bedam, ino baresi kon
@includeamin
