### ISSUE TITLE
پنل وب سایت

### ISSUE THREAD

**Issue by shahabshn** [includeamin/animup-docs#86]
mohandes mikhaim intori beshe, man tozih midam shoma bebin chikar bayad kard
baraye inke hame natonan varede panel website beshan mikhaim intori beshe ke faghat superadmin betone varede panel beshe va kasani ke tavasote superadmin dar panel permission haye lazem beheshon dade bashe, pas faghat afradi ke permission daran va superadmin mitonan az panel estefade konan va ma baghi mozaj be vorod nistan
@includeamin

**Comment by includeamin** [comment]
ye file o email kardm 
sobh didi tamas bgir 10 be bad k ba ham dar moredesh sohbat konim

**Comment by includeamin** [comment]
permission ha hameja emal shodan vali faal nashodan chon tu testim

**Comment by includeamin** [comment]
momkene bazi az jaha k ta aln login budan ya nabudan check nmishod aln dg check beshe va be shoma access denied bede
check konin k age jae k bud token phonenumber o bedim 

barresi kon be man elam kon
@shahabshn
