### ISSUE TITLE
بررسی وضعیت کلید User_Confirm

### ISSUE THREAD

**Issue by shahabshn** [includeamin/animup-docs#87]
/admin/users/status/<userId>/CONFIRM

![1](https://user-images.githubusercontent.com/47140358/66306769-65033100-e90f-11e9-9353-9216b79c0484.PNG)

@includeamin

**Comment by includeamin** [comment]
http://localhost:3002/admin/users/status/5d7397726974a40008656186/confirm
{"State": true, "Description": "CONFIRM"}
