### ISSUE TITLE
تغییر در نحوه ی معلق کردن کاربر

### ISSUE THREAD

**Issue by shahabshn** [includeamin/animup-docs#88]
mohandes baraye moalagh kardane user dar panel tedade roz mikhad, in gozine hazf beshe lotfan, zamani ke admin bekhad taiid mishe

@includeamin

**Comment by includeamin** [comment]
salam ban bar asas tarikh k ghabln bem gofte budin k normalesh 7 ruze bud  halate khasesh be tedad ruz
va jahaie dg ban budan ya nbudan hameja bar asas tarikh anjam mishe va taghire in ravand ham zaman mibare ham bug ijad mikone
ru in ghazie tajdid nazar konin
chon mn  bar asas chizi k az aval khastin zadam aln vaghan taghiresh vaght migire in mored
