### ISSUE TITLE
انیمیشن های خریدنی

### ISSUE THREAD

**Issue by shahabshn** [includeamin/animup-docs#97]
mohandes hamontor ke dar jaryani animation haye boomi ro mishe be 4 tarigh tamasha kard

1- sharje panel az dargahe khodemon
  - user mablaghe morede nazaresho entekhab mikone
  - varede dargah mishe va pardakht anjam mishe
2- sharje panel az dargahe cafebazaar
  - user mablagh ro entekhab mikone
  - az dargahe cafebazaar pardakht anjam mishe
3- sharje panel az tarighe system vas (operator)
  - user mablagh ro entekhab mikone
  - az tarighe sharje sim kart pardakht anjam mishe
4- kharide animation
  - har animation mahali ye gheymati dare
  - animation entekhab mishe
  - va az 3 raveshe (Cafebazaar, vas va dargah) pardakht sorat migire
@includeamin

**Comment by includeamin** [comment]
ino bayad telefoni sohbat konm

**Comment by includeamin** [comment]
bara inke kamel motevajeh besham va inke etelaat dargah mikham

**Comment by shahabshn** [comment]
[Bank Portal Response.docx](https://github.com/includeamin/animup-docs/files/3749872/Bank.Portal.Response.docx)
[Cafebazaar Response.docx](https://github.com/includeamin/animup-docs/files/3749873/Cafebazaar.Response.docx)
 mohandes vaziate in mozo chie?
@includeamin

**Comment by includeamin** [comment]
taghriban hame issue ha hal kardam emruz
in mozu o ishala ta akhare in hafte tamum mishe
